Start training...
dataset train metas: 4753
dataset test metas: 1078
  0%|                                                                                | 0/594 [00:00<?, ?it/s]


























































































































































































































































































































100%|█████████▉| 593/594 [10:33<00:00,  1.02it/s, Tr Loss=2.73e+3, Tr Rt=2.73e+3, Tr ph=0.0844, Tr nval=2.76]
100%|██████████| 594/594 [10:34<00:00,  1.07s/it, Tr Loss=1.95e+3, Tr Rt=1.94e+3, Tr ph=0.0934, Tr nval=3.75]
Traceback (most recent call last):
  File "C:\Dev\DL_e2e\train_e2e.py", line 442, in <module>
    train(args)
  File "C:\Dev\DL_e2e\train_e2e.py", line 286, in train
    avrg_loss, Rt_loss, ph_loss, nval_loss = validation(model_rt, model_ph, model_nval, val_loader, device, criterion_val, epoch, args)
  File "C:\Dev\DL_e2e\train_e2e.py", line 325, in validation
    total_loss, Rt_loss, ph_loss, nval_loss, cnt = 0, 0, 0, 0
ValueError: not enough values to unpack (expected 5, got 4)